import re

kana_to_phoneme_table = {
    "ア": "a",
    "イ": "i",
    "ウ": "u",
    "エ": "e",
    "オ": "o",
    "カ": "k a",
    "キ": "kj i",
    "ク": "k u",
    "ケ": "k e",
    "コ": "k o",
    "ガ": "g a",
    "ギ": "gj i",
    "グ": "g u",
    "ゲ": "g e",
    "ゴ": "g o",
    "サ": "s a",
    "シ": "sj i",
    "ス": "s u",
    "セ": "s e",
    "ソ": "s o",
    "ザ": "z a",
    "ジ": "zj i",
    "ズ": "z u",
    "ゼ": "z e",
    "ゾ": "z o",
    "タ": "t a",
    "チ": "cj i",
    "ツ": "c u",
    "テ": "t e",
    "ト": "t o",
    "ダ": "d a",
    "ヂ": "zj i",
    "ヅ": "z u",
    "デ": "d e",
    "ド": "d o",
    "ナ": "n a",
    "ニ": "nj i",
    "ヌ": "n u",
    "ネ": "n e",
    "ノ": "n o",
    "ハ": "h a",
    "ヒ": "hj i",
    "フ": "F u",
    "ヘ": "h e",
    "ホ": "h o",
    "バ": "b a",
    "ビ": "b i",
    "ブ": "b u",
    "ベ": "b e",
    "ボ": "b o",
    "パ": "p a",
    "ピ": "p i",
    "プ": "p u",
    "ペ": "p e",
    "ポ": "p o",
    "マ": "m a",
    "ミ": "m i",
    "ム": "m u",
    "メ": "m e",
    "モ": "m o",
    "ラ": "r a",
    "リ": "r i",
    "ル": "r u",
    "レ": "r e",
    "ロ": "r o",
    "ワ": "w a",
    "ヲ": "o",
    "ヤ": "y a",
    "ユ": "y u",
    "ヨ": "y o",
    "キャ": "ky a",
    "キュ": "ky u",
    "キョ": "ky o",
    "ギャ": "gy a",
    "ギュ": "gy u",
    "ギョ": "gy o",
    "シャ": "sy a",
    "シュ": "sy u",
    "ショ": "sy o",
    "ジャ": "zy a",
    "ジュ": "zy u",
    "ジョ": "zy o",
    "チャ": "cy a",
    "チュ": "cy u",
    "チョ": "cy o",
    "ヂャ": "zy a",
    "ヂュ": "zy u",
    "ヂョ": "zy o",
    "ニャ": "ny a",
    "ニュ": "ny u",
    "ニョ": "ny o",
    "ヒャ": "hy a",
    "ヒュ": "hy u",
    "ヒョ": "hy o",
    "ビャ": "by a",
    "ビュ": "by u",
    "ビョ": "by o",
    "ピャ": "py a",
    "ピュ": "py u",
    "ピェ": "py e",
    "ピョ": "py o",
    "ミャ": "my a",
    "ミュ": "my u",
    "ミョ": "my o",
    "リャ": "ry a",
    "リュ": "ry u",
    "リョ": "ry o",
    "ウィ": "w i",
    "ウェ": "w e",
    "ウォ": "w o",
    "イェ": "y e",
    "クヮ": "kw a",
    "グヮ": "gw a",
    "シェ": "sy e",
    "スィ": "s i",
    "ジェ": "zy e",
    "ズィ": "z i",
    "ティ": "t i",
    "トゥ": "t u",
    "チェ": "cy e",
    "ツァ": "c a",
    "ツィ": "c i",
    "ツェ": "c e",
    "ツォ": "c o",
    "テャ": "ty a",
    "テュ": "ty u",
    "テョ": "ty o",
    "ディ": "d i",
    "ドゥ": "d u",
    "デャ": "dy a",
    "デュ": "dy u",
    "デョ": "dy o",
    "ニェ": "ny e",
    "ヒェ": "hy e",
    "ファ": "F a",
    "フィ": "F i",
    "フェ": "F e",
    "フォ": "F o",
    "フュ": "Fy u",
    "ヴァ": "v a",
    "ヴィ": "v i",
    "ヴ": "v u",
    "ヴェ": "v e",
    "ヴォ": "v o",
    "ミェ": "my e",
    "ン": "N",
    "ッ": "Q",
    "ー": "H",
    "ァ": "a",
    "ィ": "i",
    "ゥ": "u",
    "ェ": "e",
    "ォ": "o",
    "ャ": "y a",
    "ュ": "y u",
    "ョ": "y o",
    "、": "pau",
}

# for the output of openjtalk with kana=True
alphabet_to_kana_table = {
    "Ａ": "エー",
    "Ｂ": "ビー",
    "Ｃ": "シー",
    "Ｄ": "ディー",
    "Ｅ": "イー",
    "Ｆ": "エフ",
    "Ｇ": "ジー",
    "Ｈ": "エイチ",
    "Ｉ": "アイ",
    "Ｊ": "ジェー",
    "Ｋ": "ケー",
    "Ｌ": "エル",
    "Ｍ": "エム",
    "Ｎ": "エヌ",
    "Ｏ": "オー",
    "Ｐ": "ピー",
    "Ｑ": "キュー",
    "Ｒ": "アール",
    "Ｓ": "エス",
    "Ｔ": "ティー",
    "Ｕ": "ユー",
    "Ｖ": "ヴイ",
    "Ｗ": "ダブリュー",
    "Ｘ": "エックス",
    "Ｙ": "ワイ",
    "Ｚ": "ゼット",
    "ａ": "エー",
    "ｂ": "ビー",
    "ｃ": "シー",
    "ｄ": "ディー",
    "ｅ": "イー",
    "ｆ": "エフ",
    "ｇ": "ジー",
    "ｈ": "エイチ",
    "ｉ": "アイ",
    "ｊ": "ジェー",
    "ｋ": "ケー",
    "ｌ": "エル",
    "ｍ": "エム",
    "ｎ": "エヌ",
    "ｏ": "オー",
    "ｐ": "ピー",
    "ｑ": "キュー",
    "ｒ": "アール",
    "ｓ": "エス",
    "ｔ": "ティー",
    "ｕ": "ユー",
    "ｖ": "ヴイ",
    "ｗ": "ダブリュー",
    "ｘ": "エックス",
    "ｙ": "ワイ",
    "ｚ": "ゼット",
}


# Longer keys first so digraphs (e.g. "キャ") match before single kana;
# characters not in the table are simply skipped by finditer().
_KANA_PATTERN = re.compile(
    "|".join(
        sorted(map(re.escape, kana_to_phoneme_table), key=len, reverse=True)
    )
)
_ALPHABET_TO_KANA = str.maketrans(alphabet_to_kana_table)


def kana_text_to_phoneme(kana_text: str | None) -> str:
    if kana_text is None:
        return ""

    kanas = kana_text.translate(_ALPHABET_TO_KANA)
    phonemes = [
        phoneme
        for match in _KANA_PATTERN.finditer(kanas)
        for phoneme in kana_to_phoneme_table[match.group()].split()
    ]
    return " ".join(["sil", *phonemes, "sil"])
